# Generated by Django 3.2.16 on 2022-11-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplaces',
            old_name='partner_id',
            new_name='code',
        ),
    ]
