# Generated by Django 3.2.16 on 2022-11-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='colors',
            table=None,
        ),
        migrations.AlterModelTable(
            name='variants',
            table=None,
        ),
    ]
