# Generated by Django 3.2.16 on 2022-11-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221105_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shopee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsvariantscolors',
            name='shopee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
