# Generated by Django 3.2.16 on 2022-11-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20221122_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsvariantscolors',
            name='shopee_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
