# Generated by Django 3.2.16 on 2022-11-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productsvariantscolors_shopee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='shopee_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
